<?xml version="1.0" encoding="UTF-8"?><testrun name="NodeTest (2)" project="SkipList" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="NodeTest" time="0.0">
    <testcase name="testMain" classname="NodeTest" time="0.0">
      <failure>
        <expected>Hello World!
</expected>
        <actual>Hello World!</actual>
        junit.framework.ComparisonFailure: expected:&lt;Hello World![
]&gt; but was:&lt;Hello World![]&gt;
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at student.TestCase.assertEquals(TestCase.java:799)
	at student.TestCase.assertEquals(TestCase.java:812)
	at NodeTest.testMain(NodeTest.java:25)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)


      </failure>
    </testcase>
    <testcase name="testNode" classname="NodeTest" time="0.0"/>
  </testsuite>
</testrun>
